## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [0]:
import tensorflow as tf
tf.enable_eager_execution()

In [0]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default

### Collect Data

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
import pandas as pd

In [0]:
data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/cb/prices.csv')

### Check all columns in the dataset

In [5]:
data.columns

Index([u'date', u'symbol', u'open', u'close', u'low', u'high', u'volume'], dtype='object')

### Drop columns `date` and  `symbol`

In [0]:
data = data.drop(["date","symbol"], axis = 1)

In [7]:
data.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [8]:
data_new = data.iloc[:1000]
data_new["volume"] = data_new["volume"]/1000000
data_new.head(5)

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

         open       close         low        high  volume
0  123.430000  125.839996  122.309998  126.250000  2.1636
1  125.239998  119.980003  119.940002  125.540001  2.3864
2  116.379997  114.949997  114.930000  119.739998  2.4895
3  115.480003  116.620003  113.500000  117.440002  2.0063
4  117.010002  114.970001  114.089996  117.330002  1.4086

### Divide the data into train and test sets

In [0]:
from sklearn.model_selection import train_test_split
x = data.drop(["volume"], axis = 1)
y = data[["volume"]]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1)

#### Convert Training and Test Data to numpy float32 arrays

In [0]:
import numpy as np
x_train = x_train.to_numpy('float32')

In [0]:
y_train = y_train.to_numpy('float32')
x_test = x_test.to_numpy('float32')
y_test = y_test.to_numpy('float32')

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [0]:
from sklearn.preprocessing import normalize
normalized_x_train = normalize(np.vstack([x_train]),norm='l2',axis=1)
normalized_x_test = normalize(np.vstack([x_test]),norm='l2',axis=1)

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [0]:
W = tf.random_normal(shape=[4,1], name="Weights")
b = tf.random_normal(shape=[1],name="Bias")

In [0]:
#y = tf.add(tf.matmul(np.array(normalized_x_train),W),b,name='output')
#y_test_pred = tf.add(tf.matmul(np.array(normalized_x_test),W),b,name='output')

#loss_train = tf.reduce_mean(tf.square(y-y_train),name='Loss')
#loss_test = tf.reduce_mean(tf.square(y_test_pred-y_test),name='Loss')

2.Define a function to calculate prediction

In [0]:
def fn_prediction(x,W,b):
  y= tf.add(tf.matmul(np.array(x),W),b,name='output')
  return y

def fn_loss(y,y_pred):
  loss = tf.reduce_mean(tf.square(y-y_pred),name='Loss')
  return loss

3.Loss (Cost) Function [Mean square error]

In [0]:
def fn_train(x,y,W,b,learn_rate):
  with tf.GradientTape() as t:
    t.watch([W,b])
    y_pred = fn_prediction(x,W,b)
    loss = fn_loss(y,y_pred)
    dc_dw,dc_db = t.gradient(loss,[W,b])
    print(dc_dw)
    W= W -learn_rate * dc_dw
    b= b-learn_rate * dc_db
    return W,b

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [47]:
for i in range(100):
  W,b = fn_train(normalized_x_train,y_train,W,b,0.01)
  fn_train(normalized_x_train,y_train,W,b,0.01)
  y_pred = fn_prediction(normalized_x_train,W,b)
  train_loss = fn_loss(y_train,y_pred)
  print("training loss at step :",i,"is",train_loss)
  if i % 5 == 0:
   print("training loss at 5th step :",i,"is",train_loss)

tf.Tensor(
[[ -1635.0146]
 [  1394.84  ]
 [ 15796.864 ]
 [-15010.154 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1633.8712]
 [  1395.9714]
 [ 15797.985 ]
 [-15009.046 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 0, 'is', <tf.Tensor: id=24351, shape=(), dtype=float32, numpy=152654880000000.0>)
('training loss at 5th step :', 0, 'is', <tf.Tensor: id=24351, shape=(), dtype=float32, numpy=152654880000000.0>)
tf.Tensor(
[[ -1633.8712]
 [  1395.9714]
 [ 15797.985 ]
 [-15009.046 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1632.9678]
 [  1396.8888]
 [ 15798.8545]
 [-15008.165 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 1, 'is', <tf.Tensor: id=24431, shape=(), dtype=float32, numpy=152654860000000.0>)
tf.Tensor(
[[ -1632.9678]
 [  1396.8888]
 [ 15798.8545]
 [-15008.165 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1632.0868]
 [  1397.7443]
 [ 15799.77  ]
 [-15007.276 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 2, 'is', <tf.Tensor: id=24510, shape=(), dtype=float32, numpy=152654860000000.0>)
tf.Tensor(
[[ -1632.0868]
 [  1397.7443]
 [ 15799.77  ]
 [-15007.276 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1631.2037]
 [  1398.6615]
 [ 15800.64  ]
 [-15006.337 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 3, 'is', <tf.Tensor: id=24589, shape=(), dtype=float32, numpy=152654860000000.0>)
tf.Tensor(
[[ -1631.2037]
 [  1398.6615]
 [ 15800.64  ]
 [-15006.337 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1630.3738]
 [  1399.4857]
 [ 15801.439 ]
 [-15005.5205]], shape=(4, 1), dtype=float32)
('training loss at step :', 4, 'is', <tf.Tensor: id=24668, shape=(), dtype=float32, numpy=152654860000000.0>)
tf.Tensor(
[[ -1630.3738]
 [  1399.4857]
 [ 15801.439 ]
 [-15005.5205]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1629.6049]
 [  1400.2609]
 [ 15802.1455]
 [-15004.752 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 5, 'is', <tf.Tensor: id=24747, shape=(), dtype=float32, numpy=152654850000000.0>)
('training loss at 5th step :', 5, 'is', <tf.Tensor: id=24747, shape=(), dtype=float32, numpy=152654850000000.0>)
tf.Tensor(
[[ -1629.6049]
 [  1400.2609]
 [ 15802.1455]
 [-15004.752 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1628.8478]
 [  1400.9977]
 [ 15802.854 ]
 [-15003.978 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 6, 'is', <tf.Tensor: id=24827, shape=(), dtype=float32, numpy=152654850000000.0>)
tf.Tensor(
[[ -1628.8478]
 [  1400.9977]
 [ 15802.854 ]
 [-15003.978 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1628.097 ]
 [  1401.7626]
 [ 15803.605 ]
 [-15003.182 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 7, 'is', <tf.Tensor: id=24906, shape=(), dtype=float32, numpy=152654830000000.0>)
tf.Tensor(
[[ -1628.097 ]
 [  1401.7626]
 [ 15803.605 ]
 [-15003.182 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1627.3365]
 [  1402.5167]
 [ 15804.361 ]
 [-15002.394 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 8, 'is', <tf.Tensor: id=24985, shape=(), dtype=float32, numpy=152654830000000.0>)
tf.Tensor(
[[ -1627.3365]
 [  1402.5167]
 [ 15804.361 ]
 [-15002.394 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1626.5542]
 [  1403.3021]
 [ 15805.143 ]
 [-15001.617 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 9, 'is', <tf.Tensor: id=25064, shape=(), dtype=float32, numpy=152654830000000.0>)
tf.Tensor(
[[ -1626.5542]
 [  1403.3021]
 [ 15805.143 ]
 [-15001.617 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1625.8177]
 [  1404.0602]
 [ 15805.876 ]
 [-15000.84  ]], shape=(4, 1), dtype=float32)
('training loss at step :', 10, 'is', <tf.Tensor: id=25143, shape=(), dtype=float32, numpy=152654830000000.0>)
('training loss at 5th step :', 10, 'is', <tf.Tensor: id=25143, shape=(), dtype=float32, numpy=152654830000000.0>)
tf.Tensor(
[[ -1625.8177]
 [  1404.0602]
 [ 15805.876 ]
 [-15000.84  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1625.0596]
 [  1404.814 ]
 [ 15806.645 ]
 [-14999.986 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 11, 'is', <tf.Tensor: id=25223, shape=(), dtype=float32, numpy=152654830000000.0>)
tf.Tensor(
[[ -1625.0596]
 [  1404.814 ]
 [ 15806.645 ]
 [-14999.986 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1624.3438]
 [  1405.5009]
 [ 15807.322 ]
 [-14999.244 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 12, 'is', <tf.Tensor: id=25302, shape=(), dtype=float32, numpy=152654830000000.0>)
tf.Tensor(
[[ -1624.3438]
 [  1405.5009]
 [ 15807.322 ]
 [-14999.244 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1623.6445]
 [  1406.2146]
 [ 15808.013 ]
 [-14998.522 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 13, 'is', <tf.Tensor: id=25381, shape=(), dtype=float32, numpy=152654830000000.0>)
tf.Tensor(
[[ -1623.6445]
 [  1406.2146]
 [ 15808.013 ]
 [-14998.522 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1622.9467]
 [  1406.8936]
 [ 15808.734 ]
 [-14997.888 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 14, 'is', <tf.Tensor: id=25460, shape=(), dtype=float32, numpy=152654810000000.0>)
tf.Tensor(
[[ -1622.9467]
 [  1406.8936]
 [ 15808.734 ]
 [-14997.888 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1622.2872]
 [  1407.56  ]
 [ 15809.347 ]
 [-14997.225 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 15, 'is', <tf.Tensor: id=25539, shape=(), dtype=float32, numpy=152654810000000.0>)
('training loss at 5th step :', 15, 'is', <tf.Tensor: id=25539, shape=(), dtype=float32, numpy=152654810000000.0>)
tf.Tensor(
[[ -1622.2872]
 [  1407.56  ]
 [ 15809.347 ]
 [-14997.225 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1621.6316]
 [  1408.1844]
 [ 15809.947 ]
 [-14996.567 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 16, 'is', <tf.Tensor: id=25619, shape=(), dtype=float32, numpy=152654800000000.0>)
tf.Tensor(
[[ -1621.6316]
 [  1408.1844]
 [ 15809.947 ]
 [-14996.567 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1621.2479]
 [  1408.5659]
 [ 15810.342 ]
 [-14996.173 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 17, 'is', <tf.Tensor: id=25698, shape=(), dtype=float32, numpy=152654800000000.0>)
tf.Tensor(
[[ -1621.2479]
 [  1408.5659]
 [ 15810.342 ]
 [-14996.173 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1620.8584]
 [  1408.9292]
 [ 15810.719 ]
 [-14995.767 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 18, 'is', <tf.Tensor: id=25777, shape=(), dtype=float32, numpy=152654800000000.0>)
tf.Tensor(
[[ -1620.8584]
 [  1408.9292]
 [ 15810.719 ]
 [-14995.767 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1620.4734]
 [  1409.3126]
 [ 15811.111 ]
 [-14995.394 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 19, 'is', <tf.Tensor: id=25856, shape=(), dtype=float32, numpy=152654800000000.0>)
tf.Tensor(
[[ -1620.4734]
 [  1409.3126]
 [ 15811.111 ]
 [-14995.394 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1620.0819]
 [  1409.7119]
 [ 15811.496 ]
 [-14994.963 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 20, 'is', <tf.Tensor: id=25935, shape=(), dtype=float32, numpy=152654780000000.0>)
('training loss at 5th step :', 20, 'is', <tf.Tensor: id=25935, shape=(), dtype=float32, numpy=152654780000000.0>)
tf.Tensor(
[[ -1620.0819]
 [  1409.7119]
 [ 15811.496 ]
 [-14994.963 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1619.6873]
 [  1410.0907]
 [ 15811.84  ]
 [-14994.5625]], shape=(4, 1), dtype=float32)
('training loss at step :', 21, 'is', <tf.Tensor: id=26015, shape=(), dtype=float32, numpy=152654780000000.0>)
tf.Tensor(
[[ -1619.6873]
 [  1410.0907]
 [ 15811.84  ]
 [-14994.5625]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1619.3103]
 [  1410.4736]
 [ 15812.178 ]
 [-14994.173 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 22, 'is', <tf.Tensor: id=26094, shape=(), dtype=float32, numpy=152654780000000.0>)
tf.Tensor(
[[ -1619.3103]
 [  1410.4736]
 [ 15812.178 ]
 [-14994.173 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1618.9364]
 [  1410.8567]
 [ 15812.571 ]
 [-14993.81  ]], shape=(4, 1), dtype=float32)
('training loss at step :', 23, 'is', <tf.Tensor: id=26173, shape=(), dtype=float32, numpy=152654760000000.0>)
tf.Tensor(
[[ -1618.9364]
 [  1410.8567]
 [ 15812.571 ]
 [-14993.81  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1618.5433]
 [  1411.2395]
 [ 15812.939 ]
 [-14993.415 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 24, 'is', <tf.Tensor: id=26252, shape=(), dtype=float32, numpy=152654760000000.0>)
tf.Tensor(
[[ -1618.5433]
 [  1411.2395]
 [ 15812.939 ]
 [-14993.415 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1618.2538]
 [  1411.5144]
 [ 15813.206 ]
 [-14993.162 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 25, 'is', <tf.Tensor: id=26331, shape=(), dtype=float32, numpy=152654760000000.0>)
('training loss at 5th step :', 25, 'is', <tf.Tensor: id=26331, shape=(), dtype=float32, numpy=152654760000000.0>)
tf.Tensor(
[[ -1618.2538]
 [  1411.5144]
 [ 15813.206 ]
 [-14993.162 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1617.9873]
 [  1411.7859]
 [ 15813.443 ]
 [-14992.861 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 26, 'is', <tf.Tensor: id=26411, shape=(), dtype=float32, numpy=152654750000000.0>)
tf.Tensor(
[[ -1617.9873]
 [  1411.7859]
 [ 15813.443 ]
 [-14992.861 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1617.7327]
 [  1412.042 ]
 [ 15813.692 ]
 [-14992.598 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 27, 'is', <tf.Tensor: id=26490, shape=(), dtype=float32, numpy=152654750000000.0>)
tf.Tensor(
[[ -1617.7327]
 [  1412.042 ]
 [ 15813.692 ]
 [-14992.598 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1617.4647]
 [  1412.2896]
 [ 15813.931 ]
 [-14992.3125]], shape=(4, 1), dtype=float32)
('training loss at step :', 28, 'is', <tf.Tensor: id=26569, shape=(), dtype=float32, numpy=152654730000000.0>)
tf.Tensor(
[[ -1617.4647]
 [  1412.2896]
 [ 15813.931 ]
 [-14992.3125]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1617.203 ]
 [  1412.5442]
 [ 15814.189 ]
 [-14992.025 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 29, 'is', <tf.Tensor: id=26648, shape=(), dtype=float32, numpy=152654730000000.0>)
tf.Tensor(
[[ -1617.203 ]
 [  1412.5442]
 [ 15814.189 ]
 [-14992.025 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1616.9357]
 [  1412.8262]
 [ 15814.44  ]
 [-14991.741 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 30, 'is', <tf.Tensor: id=26727, shape=(), dtype=float32, numpy=152654730000000.0>)
('training loss at 5th step :', 30, 'is', <tf.Tensor: id=26727, shape=(), dtype=float32, numpy=152654730000000.0>)
tf.Tensor(
[[ -1616.9357]
 [  1412.8262]
 [ 15814.44  ]
 [-14991.741 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1616.6814]
 [  1413.0682]
 [ 15814.676 ]
 [-14991.4795]], shape=(4, 1), dtype=float32)
('training loss at step :', 31, 'is', <tf.Tensor: id=26807, shape=(), dtype=float32, numpy=152654730000000.0>)
tf.Tensor(
[[ -1616.6814]
 [  1413.0682]
 [ 15814.676 ]
 [-14991.4795]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1616.4246]
 [  1413.3389]
 [ 15814.943 ]
 [-14991.207 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 32, 'is', <tf.Tensor: id=26886, shape=(), dtype=float32, numpy=152654730000000.0>)
tf.Tensor(
[[ -1616.4246]
 [  1413.3389]
 [ 15814.943 ]
 [-14991.207 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1616.1521]
 [  1413.5901]
 [ 15815.188 ]
 [-14990.871 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 33, 'is', <tf.Tensor: id=26965, shape=(), dtype=float32, numpy=152654710000000.0>)
tf.Tensor(
[[ -1616.1521]
 [  1413.5901]
 [ 15815.188 ]
 [-14990.871 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1615.8899]
 [  1413.8556]
 [ 15815.434 ]
 [-14990.597 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 34, 'is', <tf.Tensor: id=27044, shape=(), dtype=float32, numpy=152654710000000.0>)
tf.Tensor(
[[ -1615.8899]
 [  1413.8556]
 [ 15815.434 ]
 [-14990.597 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1615.6428]
 [  1414.1252]
 [ 15815.68  ]
 [-14990.317 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 35, 'is', <tf.Tensor: id=27123, shape=(), dtype=float32, numpy=152654710000000.0>)
('training loss at 5th step :', 35, 'is', <tf.Tensor: id=27123, shape=(), dtype=float32, numpy=152654710000000.0>)
tf.Tensor(
[[ -1615.6428]
 [  1414.1252]
 [ 15815.68  ]
 [-14990.317 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1615.3915]
 [  1414.3718]
 [ 15815.939 ]
 [-14990.055 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 36, 'is', <tf.Tensor: id=27203, shape=(), dtype=float32, numpy=152654710000000.0>)
tf.Tensor(
[[ -1615.3915]
 [  1414.3718]
 [ 15815.939 ]
 [-14990.055 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1615.1257]
 [  1414.6487]
 [ 15816.184 ]
 [-14989.762 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 37, 'is', <tf.Tensor: id=27282, shape=(), dtype=float32, numpy=152654710000000.0>)
tf.Tensor(
[[ -1615.1257]
 [  1414.6487]
 [ 15816.184 ]
 [-14989.762 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1614.8623]
 [  1414.8827]
 [ 15816.436 ]
 [-14989.474 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 38, 'is', <tf.Tensor: id=27361, shape=(), dtype=float32, numpy=152654710000000.0>)
tf.Tensor(
[[ -1614.8623]
 [  1414.8827]
 [ 15816.436 ]
 [-14989.474 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1614.592 ]
 [  1415.1483]
 [ 15816.703 ]
 [-14989.218 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 39, 'is', <tf.Tensor: id=27440, shape=(), dtype=float32, numpy=152654700000000.0>)
tf.Tensor(
[[ -1614.592 ]
 [  1415.1483]
 [ 15816.703 ]
 [-14989.218 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1614.3213]
 [  1415.4097]
 [ 15816.952 ]
 [-14988.95  ]], shape=(4, 1), dtype=float32)
('training loss at step :', 40, 'is', <tf.Tensor: id=27519, shape=(), dtype=float32, numpy=152654680000000.0>)
('training loss at 5th step :', 40, 'is', <tf.Tensor: id=27519, shape=(), dtype=float32, numpy=152654680000000.0>)
tf.Tensor(
[[ -1614.3213]
 [  1415.4097]
 [ 15816.952 ]
 [-14988.95  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1614.0814]
 [  1415.6671]
 [ 15817.196 ]
 [-14988.685 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 41, 'is', <tf.Tensor: id=27599, shape=(), dtype=float32, numpy=152654680000000.0>)
tf.Tensor(
[[ -1614.0814]
 [  1415.6671]
 [ 15817.196 ]
 [-14988.685 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1613.8177]
 [  1415.9402]
 [ 15817.446 ]
 [-14988.394 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 42, 'is', <tf.Tensor: id=27678, shape=(), dtype=float32, numpy=152654680000000.0>)
tf.Tensor(
[[ -1613.8177]
 [  1415.9402]
 [ 15817.446 ]
 [-14988.394 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1613.5565]
 [  1416.1945]
 [ 15817.689 ]
 [-14988.124 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 43, 'is', <tf.Tensor: id=27757, shape=(), dtype=float32, numpy=152654680000000.0>)
tf.Tensor(
[[ -1613.5565]
 [  1416.1945]
 [ 15817.689 ]
 [-14988.124 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1613.2888]
 [  1416.4434]
 [ 15817.929 ]
 [-14987.848 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 44, 'is', <tf.Tensor: id=27836, shape=(), dtype=float32, numpy=152654660000000.0>)
tf.Tensor(
[[ -1613.2888]
 [  1416.4434]
 [ 15817.929 ]
 [-14987.848 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1613.0146]
 [  1416.7141]
 [ 15818.201 ]
 [-14987.619 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 45, 'is', <tf.Tensor: id=27915, shape=(), dtype=float32, numpy=152654660000000.0>)
('training loss at 5th step :', 45, 'is', <tf.Tensor: id=27915, shape=(), dtype=float32, numpy=152654660000000.0>)
tf.Tensor(
[[ -1613.0146]
 [  1416.7141]
 [ 15818.201 ]
 [-14987.619 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1612.7732]
 [  1416.9666]
 [ 15818.468 ]
 [-14987.384 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 46, 'is', <tf.Tensor: id=27995, shape=(), dtype=float32, numpy=152654650000000.0>)
tf.Tensor(
[[ -1612.7732]
 [  1416.9666]
 [ 15818.468 ]
 [-14987.384 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1612.5114]
 [  1417.2406]
 [ 15818.714 ]
 [-14987.114 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 47, 'is', <tf.Tensor: id=28074, shape=(), dtype=float32, numpy=152654650000000.0>)
tf.Tensor(
[[ -1612.5114]
 [  1417.2406]
 [ 15818.714 ]
 [-14987.114 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1612.2622]
 [  1417.5117]
 [ 15818.945 ]
 [-14986.847 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 48, 'is', <tf.Tensor: id=28153, shape=(), dtype=float32, numpy=152654650000000.0>)
tf.Tensor(
[[ -1612.2622]
 [  1417.5117]
 [ 15818.945 ]
 [-14986.847 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1612.0615]
 [  1417.7181]
 [ 15819.159 ]
 [-14986.634 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 49, 'is', <tf.Tensor: id=28232, shape=(), dtype=float32, numpy=152654650000000.0>)
tf.Tensor(
[[ -1612.0615]
 [  1417.7181]
 [ 15819.159 ]
 [-14986.634 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1611.8545]
 [  1417.9004]
 [ 15819.368 ]
 [-14986.464 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 50, 'is', <tf.Tensor: id=28311, shape=(), dtype=float32, numpy=152654630000000.0>)
('training loss at 5th step :', 50, 'is', <tf.Tensor: id=28311, shape=(), dtype=float32, numpy=152654630000000.0>)
tf.Tensor(
[[ -1611.8545]
 [  1417.9004]
 [ 15819.368 ]
 [-14986.464 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1611.6453]
 [  1418.1034]
 [ 15819.558 ]
 [-14986.256 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 51, 'is', <tf.Tensor: id=28391, shape=(), dtype=float32, numpy=152654630000000.0>)
tf.Tensor(
[[ -1611.6453]
 [  1418.1034]
 [ 15819.558 ]
 [-14986.256 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1611.4487]
 [  1418.298 ]
 [ 15819.717 ]
 [-14986.084 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 52, 'is', <tf.Tensor: id=28470, shape=(), dtype=float32, numpy=152654630000000.0>)
tf.Tensor(
[[ -1611.4487]
 [  1418.298 ]
 [ 15819.717 ]
 [-14986.084 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1611.2498]
 [  1418.4968]
 [ 15819.918 ]
 [-14985.836 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 53, 'is', <tf.Tensor: id=28549, shape=(), dtype=float32, numpy=152654610000000.0>)
tf.Tensor(
[[ -1611.2498]
 [  1418.4968]
 [ 15819.918 ]
 [-14985.836 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1611.0463]
 [  1418.6998]
 [ 15820.088 ]
 [-14985.607 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 54, 'is', <tf.Tensor: id=28628, shape=(), dtype=float32, numpy=152654610000000.0>)
tf.Tensor(
[[ -1611.0463]
 [  1418.6998]
 [ 15820.088 ]
 [-14985.607 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1610.8473]
 [  1418.8835]
 [ 15820.298 ]
 [-14985.381 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 55, 'is', <tf.Tensor: id=28707, shape=(), dtype=float32, numpy=152654610000000.0>)
('training loss at 5th step :', 55, 'is', <tf.Tensor: id=28707, shape=(), dtype=float32, numpy=152654610000000.0>)
tf.Tensor(
[[ -1610.8473]
 [  1418.8835]
 [ 15820.298 ]
 [-14985.381 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1610.7108]
 [  1419.0261]
 [ 15820.42  ]
 [-14985.239 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 56, 'is', <tf.Tensor: id=28787, shape=(), dtype=float32, numpy=152654600000000.0>)
tf.Tensor(
[[ -1610.7108]
 [  1419.0261]
 [ 15820.42  ]
 [-14985.239 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1610.5951]
 [  1419.1658]
 [ 15820.551 ]
 [-14985.106 ]], shape=(4, 1), dtype=float32)
('training loss at step :', 57, 'is', <tf.Tensor: id=28866, shape=(), dtype=float32, numpy=152654600000000.0>)
tf.Tensor(
[[ -1610.5951]
 [  1419.1658]
 [ 15820.551 ]
 [-14985.106 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1610.4376]
 [  1419.2996]
 [ 15820.662 ]
 [-14984.96  ]], shape=(4, 1), dtype=float32)
('training loss at step :', 58, 'is', <tf.Tensor: id=28945, shape=(), dtype=float32, numpy=152654600000000.0>)
tf.Tensor(
[[ -1610.4376]
 [  1419.2996]

### Get the shapes and values of W and b

In [49]:
for i in range(100):
  W,b = fn_train(normalized_x_train,y_train,W,b,0.01)
  fn_train(normalized_x_train,y_train,W,b,0.01)
  y_pred = fn_prediction(normalized_x_train,W,b)
  train_loss = fn_loss(y_train,y_pred)
  print("shape of W at  :",i,"is",W)
  print("shape of b at  :",i,"is",b)

tf.Tensor(
[[ -1609.537 ]
 [  1420.1013]
 [ 15821.294 ]
 [-14983.81  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4017]
 [  1420.244 ]
 [ 15821.443 ]
 [-14983.662 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 0, 'is', <tf.Tensor: id=32225, shape=(4, 1), dtype=float32, numpy=
array([[1355251.8],
       [1343501.5],
       [1270878.6],
       [1423118.9]], dtype=float32)>)
('shape of b at  :', 0, 'is', <tf.Tensor: id=32228, shape=(1,), dtype=float32, numpy=array([2698479.2], dtype=float32)>)
tf.Tensor(
[[ -1609.4017]
 [  1420.244 ]
 [ 15821.443 ]
 [-14983.662 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5002]
 [  1420.1322]
 [ 15821.343 ]
 [-14983.775 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 1, 'is', <tf.Tensor: id=32305, shape=(4, 1), dtype=float32, numpy=
array([[1355267.9],
       [1343487.2],
       [1270720.4],
       [1423268.8]], dtype=float32)>)
('shape of b at  :', 1, 'is', <tf.Tensor: id=32308, shape=(1,), dtype=float32, numpy=array([2698480.8], dtype=float32)>)
tf.Tensor(
[[ -1609.5002]
 [  1420.1322]
 [ 15821.343 ]
 [-14983.775 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5863]
 [  1420.0026]
 [ 15821.217 ]
 [-14983.887 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 2, 'is', <tf.Tensor: id=32385, shape=(4, 1), dtype=float32, numpy=
array([[1355284. ],
       [1343473. ],
       [1270562.1],
       [1423418.6]], dtype=float32)>)
('shape of b at  :', 2, 'is', <tf.Tensor: id=32388, shape=(1,), dtype=float32, numpy=array([2698482.2], dtype=float32)>)
tf.Tensor(
[[ -1609.5863]
 [  1420.0026]
 [ 15821.217 ]
 [-14983.887 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4668]
 [  1420.1532]
 [ 15821.325 ]
 [-14983.754 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 3, 'is', <tf.Tensor: id=32465, shape=(4, 1), dtype=float32, numpy=
array([[1355300.1],
       [1343458.8],
       [1270403.9],
       [1423568.5]], dtype=float32)>)
('shape of b at  :', 3, 'is', <tf.Tensor: id=32468, shape=(1,), dtype=float32, numpy=array([2698484.], dtype=float32)>)
tf.Tensor(
[[ -1609.4668]
 [  1420.1532]
 [ 15821.325 ]
 [-14983.754 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5643]
 [  1420.0385]
 [ 15821.222 ]
 [-14983.853 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 4, 'is', <tf.Tensor: id=32545, shape=(4, 1), dtype=float32, numpy=
array([[1355316.2],
       [1343444.5],
       [1270245.6],
       [1423718.4]], dtype=float32)>)
('shape of b at  :', 4, 'is', <tf.Tensor: id=32548, shape=(1,), dtype=float32, numpy=array([2698485.5], dtype=float32)>)
tf.Tensor(
[[ -1609.5643]
 [  1420.0385]
 [ 15821.222 ]
 [-14983.853 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4187]
 [  1420.189 ]
 [ 15821.358 ]
 [-14983.705 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 5, 'is', <tf.Tensor: id=32625, shape=(4, 1), dtype=float32, numpy=
array([[1355332.4],
       [1343430.2],
       [1270087.4],
       [1423868.2]], dtype=float32)>)
('shape of b at  :', 5, 'is', <tf.Tensor: id=32628, shape=(1,), dtype=float32, numpy=array([2698487.2], dtype=float32)>)
tf.Tensor(
[[ -1609.4187]
 [  1420.189 ]
 [ 15821.358 ]
 [-14983.705 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5372]
 [  1420.0708]
 [ 15821.239 ]
 [-14983.834 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 6, 'is', <tf.Tensor: id=32705, shape=(4, 1), dtype=float32, numpy=
array([[1355348.5],
       [1343416. ],
       [1269929.1],
       [1424018.1]], dtype=float32)>)
('shape of b at  :', 6, 'is', <tf.Tensor: id=32708, shape=(1,), dtype=float32, numpy=array([2698488.8], dtype=float32)>)
tf.Tensor(
[[ -1609.5372]
 [  1420.0708]
 [ 15821.239 ]
 [-14983.834 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.3888]
 [  1420.2062]
 [ 15821.388 ]
 [-14983.698 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 7, 'is', <tf.Tensor: id=32785, shape=(4, 1), dtype=float32, numpy=
array([[1355364.6],
       [1343401.8],
       [1269770.9],
       [1424168. ]], dtype=float32)>)
('shape of b at  :', 7, 'is', <tf.Tensor: id=32788, shape=(1,), dtype=float32, numpy=array([2698490.5], dtype=float32)>)
tf.Tensor(
[[ -1609.3888]
 [  1420.2062]
 [ 15821.388 ]
 [-14983.698 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5094]
 [  1420.0957]
 [ 15821.265 ]
 [-14983.798 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 8, 'is', <tf.Tensor: id=32865, shape=(4, 1), dtype=float32, numpy=
array([[1355380.8],
       [1343387.5],
       [1269612.6],
       [1424317.9]], dtype=float32)>)
('shape of b at  :', 8, 'is', <tf.Tensor: id=32868, shape=(1,), dtype=float32, numpy=array([2698492.], dtype=float32)>)
tf.Tensor(
[[ -1609.5094]
 [  1420.0957]
 [ 15821.265 ]
 [-14983.798 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.3523]
 [  1420.2471]
 [ 15821.402 ]
 [-14983.673 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 9, 'is', <tf.Tensor: id=32945, shape=(4, 1), dtype=float32, numpy=
array([[1355396.9],
       [1343373.2],
       [1269454.4],
       [1424467.8]], dtype=float32)>)
('shape of b at  :', 9, 'is', <tf.Tensor: id=32948, shape=(1,), dtype=float32, numpy=array([2698493.8], dtype=float32)>)
tf.Tensor(
[[ -1609.3523]
 [  1420.2471]
 [ 15821.402 ]
 [-14983.673 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4697]
 [  1420.1287]
 [ 15821.27  ]
 [-14983.81  ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 10, 'is', <tf.Tensor: id=33025, shape=(4, 1), dtype=float32, numpy=
array([[1355413. ],
       [1343359. ],
       [1269296.1],
       [1424617.6]], dtype=float32)>)
('shape of b at  :', 10, 'is', <tf.Tensor: id=33028, shape=(1,), dtype=float32, numpy=array([2698495.2], dtype=float32)>)
tf.Tensor(
[[ -1609.4697]
 [  1420.1287]
 [ 15821.27  ]
 [-14983.81  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.3289]
 [  1420.2814]
 [ 15821.395 ]
 [-14983.676 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 11, 'is', <tf.Tensor: id=33105, shape=(4, 1), dtype=float32, numpy=
array([[1355429.1],
       [1343344.8],
       [1269137.9],
       [1424767.5]], dtype=float32)>)
('shape of b at  :', 11, 'is', <tf.Tensor: id=33108, shape=(1,), dtype=float32, numpy=array([2698497.], dtype=float32)>)
tf.Tensor(
[[ -1609.3289]
 [  1420.2814]
 [ 15821.395 ]
 [-14983.676 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4368]
 [  1420.1763]
 [ 15821.278 ]
 [-14983.791 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 12, 'is', <tf.Tensor: id=33185, shape=(4, 1), dtype=float32, numpy=
array([[1355445.2],
       [1343330.5],
       [1268979.6],
       [1424917.4]], dtype=float32)>)
('shape of b at  :', 12, 'is', <tf.Tensor: id=33188, shape=(1,), dtype=float32, numpy=array([2698498.5], dtype=float32)>)
tf.Tensor(
[[ -1609.4368]
 [  1420.1763]
 [ 15821.278 ]
 [-14983.791 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5461]
 [  1420.0675]
 [ 15821.151 ]
 [-14983.931 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 13, 'is', <tf.Tensor: id=33265, shape=(4, 1), dtype=float32, numpy=
array([[1355461.4],
       [1343316.2],
       [1268821.4],
       [1425067.2]], dtype=float32)>)
('shape of b at  :', 13, 'is', <tf.Tensor: id=33268, shape=(1,), dtype=float32, numpy=array([2698500.], dtype=float32)>)
tf.Tensor(
[[ -1609.5461]
 [  1420.0675]
 [ 15821.151 ]
 [-14983.931 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4177]
 [  1420.1954]
 [ 15821.273 ]
 [-14983.761 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 14, 'is', <tf.Tensor: id=33345, shape=(4, 1), dtype=float32, numpy=
array([[1355477.5],
       [1343302. ],
       [1268663.1],
       [1425217.1]], dtype=float32)>)
('shape of b at  :', 14, 'is', <tf.Tensor: id=33348, shape=(1,), dtype=float32, numpy=array([2698501.8], dtype=float32)>)
tf.Tensor(
[[ -1609.4177]
 [  1420.1954]
 [ 15821.273 ]
 [-14983.761 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5101]
 [  1420.0812]
 [ 15821.156 ]
 [-14983.894 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 15, 'is', <tf.Tensor: id=33425, shape=(4, 1), dtype=float32, numpy=
array([[1355493.6],
       [1343287.8],
       [1268504.9],
       [1425367. ]], dtype=float32)>)
('shape of b at  :', 15, 'is', <tf.Tensor: id=33428, shape=(1,), dtype=float32, numpy=array([2698503.2], dtype=float32)>)
tf.Tensor(
[[ -1609.5101]
 [  1420.0812]
 [ 15821.156 ]
 [-14983.894 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.3888]
 [  1420.2322]
 [ 15821.278 ]
 [-14983.748 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 16, 'is', <tf.Tensor: id=33505, shape=(4, 1), dtype=float32, numpy=
array([[1355509.8],
       [1343273.5],
       [1268346.6],
       [1425516.9]], dtype=float32)>)
('shape of b at  :', 16, 'is', <tf.Tensor: id=33508, shape=(1,), dtype=float32, numpy=array([2698505.], dtype=float32)>)
tf.Tensor(
[[ -1609.3888]
 [  1420.2322]
 [ 15821.278 ]
 [-14983.748 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5138]
 [  1420.1046]
 [ 15821.16  ]
 [-14983.848 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 17, 'is', <tf.Tensor: id=33585, shape=(4, 1), dtype=float32, numpy=
array([[1355525.9],
       [1343259.2],
       [1268188.4],
       [1425666.8]], dtype=float32)>)
('shape of b at  :', 17, 'is', <tf.Tensor: id=33588, shape=(1,), dtype=float32, numpy=array([2698506.5], dtype=float32)>)
tf.Tensor(
[[ -1609.5138]
 [  1420.1046]
 [ 15821.16  ]
 [-14983.848 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.3732]
 [  1420.2483]
 [ 15821.277 ]
 [-14983.699 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 18, 'is', <tf.Tensor: id=33665, shape=(4, 1), dtype=float32, numpy=
array([[1355542. ],
       [1343245. ],
       [1268030.1],
       [1425816.6]], dtype=float32)>)
('shape of b at  :', 18, 'is', <tf.Tensor: id=33668, shape=(1,), dtype=float32, numpy=array([2698508.2], dtype=float32)>)
tf.Tensor(
[[ -1609.3732]
 [  1420.2483]
 [ 15821.277 ]
 [-14983.699 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4769]
 [  1420.1387]
 [ 15821.15  ]
 [-14983.79  ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 19, 'is', <tf.Tensor: id=33745, shape=(4, 1), dtype=float32, numpy=
array([[1355558.1],
       [1343230.8],
       [1267871.9],
       [1425966.5]], dtype=float32)>)
('shape of b at  :', 19, 'is', <tf.Tensor: id=33748, shape=(1,), dtype=float32, numpy=array([2698509.8], dtype=float32)>)
tf.Tensor(
[[ -1609.4769]
 [  1420.1387]
 [ 15821.15  ]
 [-14983.79  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.3455]
 [  1420.268 ]
 [ 15821.272 ]
 [-14983.651 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 20, 'is', <tf.Tensor: id=33825, shape=(4, 1), dtype=float32, numpy=
array([[1355574.2],
       [1343216.5],
       [1267713.6],
       [1426116.4]], dtype=float32)>)
('shape of b at  :', 20, 'is', <tf.Tensor: id=33828, shape=(1,), dtype=float32, numpy=array([2698511.5], dtype=float32)>)
tf.Tensor(
[[ -1609.3455]
 [  1420.268 ]
 [ 15821.272 ]
 [-14983.651 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4381]
 [  1420.1547]
 [ 15821.159 ]
 [-14983.743 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 21, 'is', <tf.Tensor: id=33905, shape=(4, 1), dtype=float32, numpy=
array([[1355590.4],
       [1343202.2],
       [1267555.4],
       [1426266.2]], dtype=float32)>)
('shape of b at  :', 21, 'is', <tf.Tensor: id=33908, shape=(1,), dtype=float32, numpy=array([2698513.], dtype=float32)>)
tf.Tensor(
[[ -1609.4381]
 [  1420.1547]
 [ 15821.159 ]
 [-14983.743 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5593]
 [  1420.0531]
 [ 15821.059 ]
 [-14983.855 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 22, 'is', <tf.Tensor: id=33985, shape=(4, 1), dtype=float32, numpy=
array([[1355606.5],
       [1343188. ],
       [1267397.1],
       [1426416.1]], dtype=float32)>)
('shape of b at  :', 22, 'is', <tf.Tensor: id=33988, shape=(1,), dtype=float32, numpy=array([2698514.5], dtype=float32)>)
tf.Tensor(
[[ -1609.5593]
 [  1420.0531]
 [ 15821.059 ]
 [-14983.855 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4197]
 [  1420.1962]
 [ 15821.174 ]
 [-14983.719 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 23, 'is', <tf.Tensor: id=34065, shape=(4, 1), dtype=float32, numpy=
array([[1355622.6],
       [1343173.8],
       [1267238.9],
       [1426566. ]], dtype=float32)>)
('shape of b at  :', 23, 'is', <tf.Tensor: id=34068, shape=(1,), dtype=float32, numpy=array([2698516.2], dtype=float32)>)
tf.Tensor(
[[ -1609.4197]
 [  1420.1962]
 [ 15821.174 ]
 [-14983.719 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5391]
 [  1420.0874]
 [ 15821.059 ]
 [-14983.822 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 24, 'is', <tf.Tensor: id=34145, shape=(4, 1), dtype=float32, numpy=
array([[1355638.8],
       [1343159.5],
       [1267080.6],
       [1426715.9]], dtype=float32)>)
('shape of b at  :', 24, 'is', <tf.Tensor: id=34148, shape=(1,), dtype=float32, numpy=array([2698517.8], dtype=float32)>)
tf.Tensor(
[[ -1609.5391]
 [  1420.0874]
 [ 15821.059 ]
 [-14983.822 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4025]
 [  1420.2166]
 [ 15821.174 ]
 [-14983.682 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 25, 'is', <tf.Tensor: id=34225, shape=(4, 1), dtype=float32, numpy=
array([[1355654.9],
       [1343145.2],
       [1266922.4],
       [1426865.8]], dtype=float32)>)
('shape of b at  :', 25, 'is', <tf.Tensor: id=34228, shape=(1,), dtype=float32, numpy=array([2698519.5], dtype=float32)>)
tf.Tensor(
[[ -1609.4025]
 [  1420.2166]
 [ 15821.174 ]
 [-14983.682 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5126]
 [  1420.1062]
 [ 15821.065 ]
 [-14983.782 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 26, 'is', <tf.Tensor: id=34305, shape=(4, 1), dtype=float32, numpy=
array([[1355671. ],
       [1343131. ],
       [1266764.1],
       [1427015.6]], dtype=float32)>)
('shape of b at  :', 26, 'is', <tf.Tensor: id=34308, shape=(1,), dtype=float32, numpy=array([2698521.], dtype=float32)>)
tf.Tensor(
[[ -1609.5126]
 [  1420.1062]
 [ 15821.065 ]
 [-14983.782 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.3751]
 [  1420.2606]
 [ 15821.178 ]
 [-14983.621 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 27, 'is', <tf.Tensor: id=34385, shape=(4, 1), dtype=float32, numpy=
array([[1355687.1],
       [1343116.8],
       [1266605.9],
       [1427165.5]], dtype=float32)>)
('shape of b at  :', 27, 'is', <tf.Tensor: id=34388, shape=(1,), dtype=float32, numpy=array([2698522.8], dtype=float32)>)
tf.Tensor(
[[ -1609.3751]
 [  1420.2606]
 [ 15821.178 ]
 [-14983.621 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4932]
 [  1420.1366]
 [ 15821.064 ]
 [-14983.733 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 28, 'is', <tf.Tensor: id=34465, shape=(4, 1), dtype=float32, numpy=
array([[1355703.2],
       [1343102.5],
       [1266447.6],
       [1427315.4]], dtype=float32)>)
('shape of b at  :', 28, 'is', <tf.Tensor: id=34468, shape=(1,), dtype=float32, numpy=array([2698524.2], dtype=float32)>)
tf.Tensor(
[[ -1609.4932]
 [  1420.1366]
 [ 15821.064 ]
 [-14983.733 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.3502]
 [  1420.2566]
 [ 15821.201 ]
 [-14983.582 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 29, 'is', <tf.Tensor: id=34545, shape=(4, 1), dtype=float32, numpy=
array([[1355719.4],
       [1343088.2],
       [1266289.4],
       [1427465.2]], dtype=float32)>)
('shape of b at  :', 29, 'is', <tf.Tensor: id=34548, shape=(1,), dtype=float32, numpy=array([2698526.], dtype=float32)>)
tf.Tensor(
[[ -1609.3502]
 [  1420.2566]
 [ 15821.201 ]
 [-14983.582 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4683]
 [  1420.1475]
 [ 15821.065 ]
 [-14983.685 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 30, 'is', <tf.Tensor: id=34625, shape=(4, 1), dtype=float32, numpy=
array([[1355735.5],
       [1343074. ],
       [1266131.1],
       [1427615.1]], dtype=float32)>)
('shape of b at  :', 30, 'is', <tf.Tensor: id=34628, shape=(1,), dtype=float32, numpy=array([2698527.5], dtype=float32)>)
tf.Tensor(
[[ -1609.4683]
 [  1420.1475]
 [ 15821.065 ]
 [-14983.685 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.3423]
 [  1420.2837]
 [ 15821.162 ]
 [-14983.521 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 31, 'is', <tf.Tensor: id=34705, shape=(4, 1), dtype=float32, numpy=
array([[1355751.6],
       [1343059.8],
       [1265972.9],
       [1427765. ]], dtype=float32)>)
('shape of b at  :', 31, 'is', <tf.Tensor: id=34708, shape=(1,), dtype=float32, numpy=array([2698529.2], dtype=float32)>)
tf.Tensor(
[[ -1609.3423]
 [  1420.2837]
 [ 15821.162 ]
 [-14983.521 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4537]
 [  1420.1747]
 [ 15821.066 ]
 [-14983.644 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 32, 'is', <tf.Tensor: id=34785, shape=(4, 1), dtype=float32, numpy=
array([[1355767.8],
       [1343045.5],
       [1265814.6],
       [1427914.9]], dtype=float32)>)
('shape of b at  :', 32, 'is', <tf.Tensor: id=34788, shape=(1,), dtype=float32, numpy=array([2698530.8], dtype=float32)>)
tf.Tensor(
[[ -1609.4537]
 [  1420.1747]
 [ 15821.066 ]
 [-14983.644 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.3112]
 [  1420.3055]
 [ 15821.183 ]
 [-14983.478 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 33, 'is', <tf.Tensor: id=34865, shape=(4, 1), dtype=float32, numpy=
array([[1355783.9],
       [1343031.2],
       [1265656.4],
       [1428064.8]], dtype=float32)>)
('shape of b at  :', 33, 'is', <tf.Tensor: id=34868, shape=(1,), dtype=float32, numpy=array([2698532.5], dtype=float32)>)
tf.Tensor(
[[ -1609.3112]
 [  1420.3055]
 [ 15821.183 ]
 [-14983.478 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4343]
 [  1420.202 ]
 [ 15821.075 ]
 [-14983.612 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 34, 'is', <tf.Tensor: id=34945, shape=(4, 1), dtype=float32, numpy=
array([[1355800. ],
       [1343017. ],
       [1265498.1],
       [1428214.6]], dtype=float32)>)
('shape of b at  :', 34, 'is', <tf.Tensor: id=34948, shape=(1,), dtype=float32, numpy=array([2698534.], dtype=float32)>)
tf.Tensor(
[[ -1609.4343]
 [  1420.202 ]
 [ 15821.075 ]
 [-14983.612 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5629]
 [  1420.0685]
 [ 15820.942 ]
 [-14983.714 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 35, 'is', <tf.Tensor: id=35025, shape=(4, 1), dtype=float32, numpy=
array([[1355816.1],
       [1343002.8],
       [1265339.9],
       [1428364.5]], dtype=float32)>)
('shape of b at  :', 35, 'is', <tf.Tensor: id=35028, shape=(1,), dtype=float32, numpy=array([2698535.5], dtype=float32)>)
tf.Tensor(
[[ -1609.5629]
 [  1420.0685]
 [ 15820.942 ]
 [-14983.714 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.4194]
 [  1420.2108]
 [ 15821.103 ]
 [-14983.579 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 36, 'is', <tf.Tensor: id=35105, shape=(4, 1), dtype=float32, numpy=
array([[1355832.2],
       [1342988.5],
       [1265181.6],
       [1428514.4]], dtype=float32)>)
('shape of b at  :', 36, 'is', <tf.Tensor: id=35108, shape=(1,), dtype=float32, numpy=array([2698537.2], dtype=float32)>)
tf.Tensor(
[[ -1609.4194]
 [  1420.2108]
 [ 15821.103 ]
 [-14983.579 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.5242]
 [  1420.0856]
 [ 15820.973 ]
 [-14983.695 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 37, 'is', <tf.Tensor: id=35185, shape=(4, 1), dtype=float32, numpy=
array([[1355848.4],
       [1342974.2],
       [1265023.4],
       [1428664.2]], dtype=float32)>)
('shape of b at  :', 37, 'is', <tf.Tensor: id=35188, shape=(1,), dtype=float32, numpy=array([2698538.8], dtype=float32)>)
tf.Tensor(
[[ -1609.5242]
 [  1420.0856]
 [ 15820.973 ]
 [-14983.695 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1609.388 ]
 [  1420.2454]
 [ 15821.104 ]
 [-14983.557 ]], shape=(4, 1), dtype=float32)
('shape of W at  :', 38, 'is', <tf.Tensor: id=35265, shape=(4, 1), dtype=float32, numpy=
array([[1355864.5],
       [1342960. ],
       [1264865.1],
       [1428814.1]], dtype=float32)>)
('shape of b at  :', 38, 'is', <tf.Tensor: id=35268, shape=(1,), dtype=float32, numpy=array([2698540.5], dtype=float32)>)
tf.Tensor(

### Model Prediction on 1st Examples in Test Dataset

In [51]:
for i in range(100):
  W,b = fn_train(normalized_x_test,y_test,W,b,0.01)
  fn_train(normalized_x_test,y_test,W,b,0.01)
  y_pred = fn_prediction(normalized_x_test,W,b)
  train_loss = fn_loss(y_test,y_pred)
  if i % 1 == 0:
    print("training loss at 1st step :",i,"is",train_loss)
    print("y_pred loss at 1st step :",i,"is",y_pred)

tf.Tensor(
[[ -2111.7856]
 [  1101.7484]
 [ 15427.51  ]
 [-16701.113 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -2081.9202]
 [  1131.6223]
 [ 15457.039 ]
 [-16670.78  ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 0, 'is', <tf.Tensor: id=48111, shape=(), dtype=float32, numpy=163486170000000.0>)
('y_pred loss at 1st step :', 0, 'is', <tf.Tensor: id=48106, shape=(255380, 1), dtype=float32, numpy=
array([[5439303. ],
       [5438604. ],
       [5439109.5],
       ...,
       [5438598. ],
       [5438950.5],
       [5438826.5]], dtype=float32)>)
tf.Tensor(
[[ -2081.9202]
 [  1131.6223]
 [ 15457.039 ]
 [-16670.78  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -2053.4587]
 [  1160.1758]
 [ 15485.294 ]
 [-16642.14  ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 1, 'is', <tf.Tensor: id=48191, shape=(), dtype=float32, numpy=163486150000000.0>)
('y_pred loss at 1st step :', 1, 'is', <tf.Tensor: id=48186, shape=(255380, 1), dtype=float32, numpy=
array([[5439332. ],
       [5438631.5],
       [5439138. ],
       ...,
       [5438626. ],
       [5438978.5],
       [5438854.5]], dtype=float32)>)
tf.Tensor(
[[ -2053.4587]
 [  1160.1758]
 [ 15485.294 ]
 [-16642.14  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -2026.0731]
 [  1187.5771]
 [ 15512.399 ]
 [-16614.314 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 2, 'is', <tf.Tensor: id=48271, shape=(), dtype=float32, numpy=163486150000000.0>)
('y_pred loss at 1st step :', 2, 'is', <tf.Tensor: id=48266, shape=(255380, 1), dtype=float32, numpy=
array([[5439360. ],
       [5438658. ],
       [5439165.5],
       ...,
       [5438652. ],
       [5439006. ],
       [5438881.5]], dtype=float32)>)
tf.Tensor(
[[ -2026.0731]
 [  1187.5771]
 [ 15512.399 ]
 [-16614.314 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1999.6893]
 [  1213.981 ]
 [ 15538.52  ]
 [-16587.648 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 3, 'is', <tf.Tensor: id=48351, shape=(), dtype=float32, numpy=163486150000000.0>)
('y_pred loss at 1st step :', 3, 'is', <tf.Tensor: id=48346, shape=(255380, 1), dtype=float32, numpy=
array([[5439386.5],
       [5438683.5],
       [5439192. ],
       ...,
       [5438678. ],
       [5439032. ],
       [5438907.5]], dtype=float32)>)
tf.Tensor(
[[ -1999.6893]
 [  1213.981 ]
 [ 15538.52  ]
 [-16587.648 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1974.2467]
 [  1239.3348]
 [ 15563.584 ]
 [-16561.99  ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 4, 'is', <tf.Tensor: id=48431, shape=(), dtype=float32, numpy=163486150000000.0>)
('y_pred loss at 1st step :', 4, 'is', <tf.Tensor: id=48426, shape=(255380, 1), dtype=float32, numpy=
array([[5439412. ],
       [5438708. ],
       [5439218. ],
       ...,
       [5438702.5],
       [5439057. ],
       [5438932. ]], dtype=float32)>)
tf.Tensor(
[[ -1974.2467]
 [  1239.3348]
 [ 15563.584 ]
 [-16561.99  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1949.8369]
 [  1263.7871]
 [ 15587.718 ]
 [-16537.28  ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 5, 'is', <tf.Tensor: id=48511, shape=(), dtype=float32, numpy=163486150000000.0>)
('y_pred loss at 1st step :', 5, 'is', <tf.Tensor: id=48506, shape=(255380, 1), dtype=float32, numpy=
array([[5439437. ],
       [5438732. ],
       [5439242. ],
       ...,
       [5438726. ],
       [5439081. ],
       [5438956.5]], dtype=float32)>)
tf.Tensor(
[[ -1949.8369]
 [  1263.7871]
 [ 15587.718 ]
 [-16537.28  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1926.4891]
 [  1287.05  ]
 [ 15610.846 ]
 [-16513.742 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 6, 'is', <tf.Tensor: id=48591, shape=(), dtype=float32, numpy=163486150000000.0>)
('y_pred loss at 1st step :', 6, 'is', <tf.Tensor: id=48586, shape=(255380, 1), dtype=float32, numpy=
array([[5439461. ],
       [5438754. ],
       [5439266. ],
       ...,
       [5438748.5],
       [5439104. ],
       [5438979. ]], dtype=float32)>)
tf.Tensor(
[[ -1926.4891]
 [  1287.05  ]
 [ 15610.846 ]
 [-16513.742 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1904.213 ]
 [  1309.5262]
 [ 15632.977 ]
 [-16490.998 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 7, 'is', <tf.Tensor: id=48671, shape=(), dtype=float32, numpy=163486130000000.0>)
('y_pred loss at 1st step :', 7, 'is', <tf.Tensor: id=48666, shape=(255380, 1), dtype=float32, numpy=
array([[5439484. ],
       [5438776. ],
       [5439288. ],
       ...,
       [5438770. ],
       [5439126.5],
       [5439001. ]], dtype=float32)>)
tf.Tensor(
[[ -1904.213 ]
 [  1309.5262]
 [ 15632.977 ]
 [-16490.998 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1882.6945]
 [  1330.9309]
 [ 15654.101 ]
 [-16469.31  ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 8, 'is', <tf.Tensor: id=48751, shape=(), dtype=float32, numpy=163486120000000.0>)
('y_pred loss at 1st step :', 8, 'is', <tf.Tensor: id=48746, shape=(255380, 1), dtype=float32, numpy=
array([[5439505.5],
       [5438796. ],
       [5439310. ],
       ...,
       [5438790.5],
       [5439147.5],
       [5439022. ]], dtype=float32)>)
tf.Tensor(
[[ -1882.6945]
 [  1330.9309]
 [ 15654.101 ]
 [-16469.31  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1861.8168]
 [  1351.8108]
 [ 15674.809 ]
 [-16448.357 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 9, 'is', <tf.Tensor: id=48831, shape=(), dtype=float32, numpy=163486120000000.0>)
('y_pred loss at 1st step :', 9, 'is', <tf.Tensor: id=48826, shape=(255380, 1), dtype=float32, numpy=
array([[5439527. ],
       [5438816.5],
       [5439331. ],
       ...,
       [5438811. ],
       [5439168. ],
       [5439042.5]], dtype=float32)>)
tf.Tensor(
[[ -1861.8168]
 [  1351.8108]
 [ 15674.809 ]
 [-16448.357 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1841.929 ]
 [  1371.7242]
 [ 15694.478 ]
 [-16428.24  ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 10, 'is', <tf.Tensor: id=48911, shape=(), dtype=float32, numpy=163486120000000.0>)
('y_pred loss at 1st step :', 10, 'is', <tf.Tensor: id=48906, shape=(255380, 1), dtype=float32, numpy=
array([[5439547. ],
       [5438835.5],
       [5439351. ],
       ...,
       [5438830. ],
       [5439188. ],
       [5439062. ]], dtype=float32)>)
tf.Tensor(
[[ -1841.929 ]
 [  1371.7242]
 [ 15694.478 ]
 [-16428.24  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1823.0011]
 [  1390.639 ]
 [ 15713.131 ]
 [-16409.045 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 11, 'is', <tf.Tensor: id=48991, shape=(), dtype=float32, numpy=163486120000000.0>)
('y_pred loss at 1st step :', 11, 'is', <tf.Tensor: id=48986, shape=(255380, 1), dtype=float32, numpy=
array([[5439566.5],
       [5438853.5],
       [5439370. ],
       ...,
       [5438848. ],
       [5439207. ],
       [5439080. ]], dtype=float32)>)
tf.Tensor(
[[ -1823.0011]
 [  1390.639 ]
 [ 15713.131 ]
 [-16409.045 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1804.6941]
 [  1409.0104]
 [ 15731.351 ]
 [-16390.645 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 12, 'is', <tf.Tensor: id=49071, shape=(), dtype=float32, numpy=163486100000000.0>)
('y_pred loss at 1st step :', 12, 'is', <tf.Tensor: id=49066, shape=(255380, 1), dtype=float32, numpy=
array([[5439585. ],
       [5438871. ],
       [5439388. ],
       ...,
       [5438865. ],
       [5439225. ],
       [5439098.5]], dtype=float32)>)
tf.Tensor(
[[ -1804.6941]
 [  1409.0104]
 [ 15731.351 ]
 [-16390.645 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1787.1906]
 [  1426.408 ]
 [ 15748.498 ]
 [-16373.069 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 13, 'is', <tf.Tensor: id=49151, shape=(), dtype=float32, numpy=163486080000000.0>)
('y_pred loss at 1st step :', 13, 'is', <tf.Tensor: id=49146, shape=(255380, 1), dtype=float32, numpy=
array([[5439603. ],
       [5438887.5],
       [5439406. ],
       ...,
       [5438882. ],
       [5439242. ],
       [5439115. ]], dtype=float32)>)
tf.Tensor(
[[ -1787.1906]
 [  1426.408 ]
 [ 15748.498 ]
 [-16373.069 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1770.3881]
 [  1443.2596]
 [ 15765.257 ]
 [-16355.827 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 14, 'is', <tf.Tensor: id=49231, shape=(), dtype=float32, numpy=163486080000000.0>)
('y_pred loss at 1st step :', 14, 'is', <tf.Tensor: id=49226, shape=(255380, 1), dtype=float32, numpy=
array([[5439620. ],
       [5438903.5],
       [5439423. ],
       ...,
       [5438898. ],
       [5439259. ],
       [5439132. ]], dtype=float32)>)
tf.Tensor(
[[ -1770.3881]
 [  1443.2596]
 [ 15765.257 ]
 [-16355.827 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1754.0167]
 [  1459.5944]
 [ 15781.4   ]
 [-16339.29  ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 15, 'is', <tf.Tensor: id=49311, shape=(), dtype=float32, numpy=163486080000000.0>)
('y_pred loss at 1st step :', 15, 'is', <tf.Tensor: id=49306, shape=(255380, 1), dtype=float32, numpy=
array([[5439637. ],
       [5438919. ],
       [5439439. ],
       ...,
       [5438913.5],
       [5439275. ],
       [5439147.5]], dtype=float32)>)
tf.Tensor(
[[ -1754.0167]
 [  1459.5944]
 [ 15781.4   ]
 [-16339.29  ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1738.6459]
 [  1474.9835]
 [ 15796.607 ]
 [-16323.807 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 16, 'is', <tf.Tensor: id=49391, shape=(), dtype=float32, numpy=163486080000000.0>)
('y_pred loss at 1st step :', 16, 'is', <tf.Tensor: id=49386, shape=(255380, 1), dtype=float32, numpy=
array([[5439653. ],
       [5438934. ],
       [5439455. ],
       ...,
       [5438928. ],
       [5439290. ],
       [5439162.5]], dtype=float32)>)
tf.Tensor(
[[ -1738.6459]
 [  1474.9835]
 [ 15796.607 ]
 [-16323.807 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1723.7333]
 [  1489.9069]
 [ 15811.33  ]
 [-16308.747 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 17, 'is', <tf.Tensor: id=49471, shape=(), dtype=float32, numpy=163486080000000.0>)
('y_pred loss at 1st step :', 17, 'is', <tf.Tensor: id=49466, shape=(255380, 1), dtype=float32, numpy=
array([[5439668. ],
       [5438948. ],
       [5439470. ],
       ...,
       [5438942. ],
       [5439304.5],
       [5439177. ]], dtype=float32)>)
tf.Tensor(
[[ -1723.7333]
 [  1489.9069]
 [ 15811.33  ]
 [-16308.747 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1709.3878]
 [  1504.3031]
 [ 15825.577 ]
 [-16294.051 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 18, 'is', <tf.Tensor: id=49551, shape=(), dtype=float32, numpy=163486070000000.0>)
('y_pred loss at 1st step :', 18, 'is', <tf.Tensor: id=49546, shape=(255380, 1), dtype=float32, numpy=
array([[5439683. ],
       [5438961.5],
       [5439484. ],
       ...,
       [5438955.5],
       [5439319. ],
       [5439191. ]], dtype=float32)>)
tf.Tensor(
[[ -1709.3878]
 [  1504.3031]
 [ 15825.577 ]
 [-16294.051 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1695.4678]
 [  1518.1694]
 [ 15839.264 ]
 [-16280.158 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 19, 'is', <tf.Tensor: id=49631, shape=(), dtype=float32, numpy=163486070000000.0>)
('y_pred loss at 1st step :', 19, 'is', <tf.Tensor: id=49626, shape=(255380, 1), dtype=float32, numpy=
array([[5439697. ],
       [5438974.5],
       [5439498.5],
       ...,
       [5438969. ],
       [5439332. ],
       [5439204.5]], dtype=float32)>)
tf.Tensor(
[[ -1695.4678]
 [  1518.1694]
 [ 15839.264 ]
 [-16280.158 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1682.239]
 [  1531.504]
 [ 15852.446]
 [-16266.833]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 20, 'is', <tf.Tensor: id=49711, shape=(), dtype=float32, numpy=163486050000000.0>)
('y_pred loss at 1st step :', 20, 'is', <tf.Tensor: id=49706, shape=(255380, 1), dtype=float32, numpy=
array([[5439711. ],
       [5438987. ],
       [5439512. ],
       ...,
       [5438981. ],
       [5439345.5],
       [5439217. ]], dtype=float32)>)
tf.Tensor(
[[ -1682.239]
 [  1531.504]
 [ 15852.446]
 [-16266.833]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1669.3174]
 [  1544.3356]
 [ 15865.039 ]
 [-16253.766 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 21, 'is', <tf.Tensor: id=49791, shape=(), dtype=float32, numpy=163486050000000.0>)
('y_pred loss at 1st step :', 21, 'is', <tf.Tensor: id=49786, shape=(255380, 1), dtype=float32, numpy=
array([[5439724. ],
       [5438999. ],
       [5439524.5],
       ...,
       [5438993. ],
       [5439358. ],
       [5439229.5]], dtype=float32)>)
tf.Tensor(
[[ -1669.3174]
 [  1544.3356]
 [ 15865.039 ]
 [-16253.766 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1657.3921]
 [  1556.3115]
 [ 15876.962 ]
 [-16241.484 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 22, 'is', <tf.Tensor: id=49871, shape=(), dtype=float32, numpy=163486050000000.0>)
('y_pred loss at 1st step :', 22, 'is', <tf.Tensor: id=49866, shape=(255380, 1), dtype=float32, numpy=
array([[5439737.],
       [5439010.],
       [5439537.],
       ...,
       [5439004.],
       [5439370.],
       [5439241.]], dtype=float32)>)
tf.Tensor(
[[ -1657.3921]
 [  1556.3115]
 [ 15876.962 ]
 [-16241.484 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1645.562 ]
 [  1568.0641]
 [ 15888.583 ]
 [-16229.604 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 23, 'is', <tf.Tensor: id=49951, shape=(), dtype=float32, numpy=163486050000000.0>)
('y_pred loss at 1st step :', 23, 'is', <tf.Tensor: id=49946, shape=(255380, 1), dtype=float32, numpy=
array([[5439749. ],
       [5439021. ],
       [5439549. ],
       ...,
       [5439015. ],
       [5439381. ],
       [5439252.5]], dtype=float32)>)
tf.Tensor(
[[ -1645.562 ]
 [  1568.0641]
 [ 15888.583 ]
 [-16229.604 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1634.2972]
 [  1579.4147]
 [ 15899.772 ]
 [-16218.205 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 24, 'is', <tf.Tensor: id=50031, shape=(), dtype=float32, numpy=163486030000000.0>)
('y_pred loss at 1st step :', 24, 'is', <tf.Tensor: id=50026, shape=(255380, 1), dtype=float32, numpy=
array([[5439760.5],
       [5439031.5],
       [5439560. ],
       ...,
       [5439025.5],
       [5439392. ],
       [5439263. ]], dtype=float32)>)
tf.Tensor(
[[ -1634.2972]
 [  1579.4147]
 [ 15899.772 ]
 [-16218.205 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1623.4916]
 [  1590.1936]
 [ 15910.483 ]
 [-16207.435 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 25, 'is', <tf.Tensor: id=50111, shape=(), dtype=float32, numpy=163486030000000.0>)
('y_pred loss at 1st step :', 25, 'is', <tf.Tensor: id=50106, shape=(255380, 1), dtype=float32, numpy=
array([[5439772. ],
       [5439041.5],
       [5439571. ],
       ...,
       [5439036. ],
       [5439403. ],
       [5439273.5]], dtype=float32)>)
tf.Tensor(
[[ -1623.4916]
 [  1590.1936]
 [ 15910.483 ]
 [-16207.435 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1613.002]
 [  1600.68 ]
 [ 15920.749]
 [-16196.794]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 26, 'is', <tf.Tensor: id=50191, shape=(), dtype=float32, numpy=163486030000000.0>)
('y_pred loss at 1st step :', 26, 'is', <tf.Tensor: id=50186, shape=(255380, 1), dtype=float32, numpy=
array([[5439783. ],
       [5439051. ],
       [5439581.5],
       ...,
       [5439045. ],
       [5439413. ],
       [5439283.5]], dtype=float32)>)
tf.Tensor(
[[ -1613.002]
 [  1600.68 ]
 [ 15920.749]
 [-16196.794]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1603.2031]
 [  1610.5116]
 [ 15930.5205]
 [-16186.8   ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 27, 'is', <tf.Tensor: id=50271, shape=(), dtype=float32, numpy=163486020000000.0>)
('y_pred loss at 1st step :', 27, 'is', <tf.Tensor: id=50266, shape=(255380, 1), dtype=float32, numpy=
array([[5439793.],
       [5439060.],
       [5439592.],
       ...,
       [5439054.],
       [5439423.],
       [5439293.]], dtype=float32)>)
tf.Tensor(
[[ -1603.2031]
 [  1610.5116]
 [ 15930.5205]
 [-16186.8   ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1593.7484]
 [  1619.967 ]
 [ 15939.899 ]
 [-16177.162 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 28, 'is', <tf.Tensor: id=50351, shape=(), dtype=float32, numpy=163486020000000.0>)
('y_pred loss at 1st step :', 28, 'is', <tf.Tensor: id=50346, shape=(255380, 1), dtype=float32, numpy=
array([[5439803.],
       [5439069.],
       [5439601.],
       ...,
       [5439063.],
       [5439432.],
       [5439302.]], dtype=float32)>)
tf.Tensor(
[[ -1593.7484]
 [  1619.967 ]
 [ 15939.899 ]
 [-16177.162 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1584.7343]
 [  1628.9419]
 [ 15948.744 ]
 [-16167.992 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 29, 'is', <tf.Tensor: id=50431, shape=(), dtype=float32, numpy=163486020000000.0>)
('y_pred loss at 1st step :', 29, 'is', <tf.Tensor: id=50426, shape=(255380, 1), dtype=float32, numpy=
array([[5439812. ],
       [5439077. ],
       [5439610. ],
       ...,
       [5439071. ],
       [5439441. ],
       [5439310.5]], dtype=float32)>)
tf.Tensor(
[[ -1584.7343]
 [  1628.9419]
 [ 15948.744 ]
 [-16167.992 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1575.9054]
 [  1637.7877]
 [ 15957.452 ]
 [-16159.151 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 30, 'is', <tf.Tensor: id=50511, shape=(), dtype=float32, numpy=163486020000000.0>)
('y_pred loss at 1st step :', 30, 'is', <tf.Tensor: id=50506, shape=(255380, 1), dtype=float32, numpy=
array([[5439821.5],
       [5439085. ],
       [5439619. ],
       ...,
       [5439079. ],
       [5439449. ],
       [5439319. ]], dtype=float32)>)
tf.Tensor(
[[ -1575.9054]
 [  1637.7877]
 [ 15957.452 ]
 [-16159.151 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1567.5068]
 [  1646.1294]
 [ 15965.73  ]
 [-16150.806 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 31, 'is', <tf.Tensor: id=50591, shape=(), dtype=float32, numpy=163486000000000.0>)
('y_pred loss at 1st step :', 31, 'is', <tf.Tensor: id=50586, shape=(255380, 1), dtype=float32, numpy=
array([[5439830. ],
       [5439092.5],
       [5439628. ],
       ...,
       [5439086.5],
       [5439457. ],
       [5439327. ]], dtype=float32)>)
tf.Tensor(
[[ -1567.5068]
 [  1646.1294]
 [ 15965.73  ]
 [-16150.806 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1559.649]
 [  1654.125]
 [ 15973.624]
 [-16142.964]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 32, 'is', <tf.Tensor: id=50671, shape=(), dtype=float32, numpy=163486000000000.0>)
('y_pred loss at 1st step :', 32, 'is', <tf.Tensor: id=50666, shape=(255380, 1), dtype=float32, numpy=
array([[5439839. ],
       [5439099.5],
       [5439636. ],
       ...,
       [5439093.5],
       [5439465. ],
       [5439334.5]], dtype=float32)>)
tf.Tensor(
[[ -1559.649]
 [  1654.125]
 [ 15973.624]
 [-16142.964]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1551.7068]
 [  1661.9637]
 [ 15981.38  ]
 [-16134.839 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 33, 'is', <tf.Tensor: id=50751, shape=(), dtype=float32, numpy=163485980000000.0>)
('y_pred loss at 1st step :', 33, 'is', <tf.Tensor: id=50746, shape=(255380, 1), dtype=float32, numpy=
array([[5439847. ],
       [5439106.5],
       [5439644. ],
       ...,
       [5439100.5],
       [5439473. ],
       [5439342. ]], dtype=float32)>)
tf.Tensor(
[[ -1551.7068]
 [  1661.9637]
 [ 15981.38  ]
 [-16134.839 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[ -1544.357 ]
 [  1669.3481]
 [ 15988.637 ]
 [-16127.363 ]], shape=(4, 1), dtype=float32)
('training loss at 1st step :', 34, 'is', <tf.Tensor: id=50831, shape=(), dtype=float32, numpy=163485980000000.0>)
('y_pred loss at 1st step :', 34, 'is', <tf.Tensor: id=50826, shape=(255380, 1), dtype=float32, numpy=
array([[5439855. ],
       [5439113. ],
       [5439651.5],
       ...,
       [5439107. ],
       [5439480. ],
       [5439349. ]], dtype=float32)>)
tf.Tensor(
[[ -1544.357 ]
 [  1669.3481]

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

In [0]:
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/cb/11_Iris.csv')

In [0]:
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [0]:
dataset = pd.get_dummies(dataset,columns=["Species"])

In [0]:
X = dataset.iloc[:,1:5]
Y = dataset.iloc[:,5:8]

### Splitting the data into feature set and target set

In [0]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=1)

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function

In [0]:
	# create model
model = tf.keras.Sequential()
#model.add(tf.keras.layers.Dense(8, input_dim=4, activation='relu'))
model.add(tf.keras.layers.Dense(3, input_shape=(4,),activation='softmax'))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [106]:
model.fit(x_train, y_train, validation_data=(x_test,y_test),epochs=150, batch_size=10)

W0721 13:28:57.286921 140246524905344 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_grad.py:1250: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 105 samples, validate on 45 samples
Epoch 1/150
105/105 [==============================] - 1s 5ms/sample - loss: 2.1824 - acc: 0.3429 - val_loss: 1.2510 - val_acc: 0.5111
Epoch 2/150
105/105 [==============================] - 0s 192us/sample - loss: 1.2276 - acc: 0.2476 - val_loss: 1.0705 - val_acc: 0.5111
Epoch 3/150
105/105 [==============================] - 0s 172us/sample - loss: 1.0987 - acc: 0.3524 - val_loss: 1.0269 - val_acc: 0.4000
Epoch 4/150
105/105 [==============================] - 0s 177us/sample - loss: 1.0208 - acc: 0.3810 - val_loss: 1.0730 - val_acc: 0.3778
Epoch 5/150
105/105 [==============================] - 0s 183us/sample - loss: 0.9796 - acc: 0.4857 - val_loss: 0.9244 - val_acc: 0.5333
Epoch 6/150
105/105 [==============================] - 0s 176us/sample - loss: 0.9167 - acc: 0.5810 - val_loss: 0.8713 - val_acc: 0.4444
Epoch 7/150
105/105 [==============================] - 0s 171us/sample - loss: 0.8767 - acc: 0.5429 - val_loss: 0.9114 - val_acc: 0.6000
Epoch 8/150
105/105 [==============================] - 0s 180us/sample - loss: 0.8536 - acc: 0.6286 - val_loss: 0.8142 - val_acc: 0.5333
Epoch 9/150
105/105 [==============================] - 0s 182us/sample - loss: 0.8065 - acc: 0.5429 - val_loss: 0.8304 - val_acc: 0.5778
Epoch 10/150
105/105 [==============================] - 0s 182us/sample - loss: 0.7805 - acc: 0.6286 - val_loss: 0.8979 - val_acc: 0.6000
Epoch 11/150
105/105 [==============================] - 0s 194us/sample - loss: 0.7801 - acc: 0.6571 - val_loss: 0.7978 - val_acc: 0.6000
Epoch 12/150
105/105 [==============================] - 0s 173us/sample - loss: 0.7398 - acc: 0.6571 - val_loss: 0.7640 - val_acc: 0.6000
Epoch 13/150
105/105 [==============================] - 0s 165us/sample - loss: 0.7179 - acc: 0.6667 - val_loss: 0.7241 - val_acc: 0.5778
Epoch 14/150
105/105 [==============================] - 0s 173us/sample - loss: 0.6935 - acc: 0.6286 - val_loss: 0.7326 - val_acc: 0.5778
Epoch 15/150
105/105 [==============================] - 0s 207us/sample - loss: 0.6870 - acc: 0.6762 - val_loss: 0.7175 - val_acc: 0.5778
Epoch 16/150
105/105 [==============================] - 0s 172us/sample - loss: 0.6785 - acc: 0.6571 - val_loss: 0.6726 - val_acc: 0.5556
Epoch 17/150
105/105 [==============================] - 0s 198us/sample - loss: 0.6538 - acc: 0.6476 - val_loss: 0.7391 - val_acc: 0.6000
Epoch 18/150
105/105 [==============================] - 0s 166us/sample - loss: 0.6510 - acc: 0.6857 - val_loss: 0.6647 - val_acc: 0.5778
Epoch 19/150
105/105 [==============================] - 0s 223us/sample - loss: 0.6331 - acc: 0.6762 - val_loss: 0.6495 - val_acc: 0.5778
Epoch 20/150
105/105 [==============================] - 0s 213us/sample - loss: 0.6224 - acc: 0.6952 - val_loss: 0.6271 - val_acc: 0.6000
Epoch 21/150
105/105 [==============================] - 0s 189us/sample - loss: 0.6168 - acc: 0.6667 - val_loss: 0.6204 - val_acc: 0.6000
Epoch 22/150
105/105 [==============================] - 0s 180us/sample - loss: 0.6070 - acc: 0.6952 - val_loss: 0.6306 - val_acc: 0.6000
Epoch 23/150
105/105 [==============================] - 0s 184us/sample - loss: 0.5903 - acc: 0.7143 - val_loss: 0.6620 - val_acc: 0.6000
Epoch 24/150
105/105 [==============================] - 0s 189us/sample - loss: 0.5859 - acc: 0.6952 - val_loss: 0.5910 - val_acc: 0.7778
Epoch 25/150
105/105 [==============================] - 0s 179us/sample - loss: 0.5832 - acc: 0.6952 - val_loss: 0.6115 - val_acc: 0.6000
Epoch 26/150
105/105 [==============================] - 0s 183us/sample - loss: 0.5671 - acc: 0.6952 - val_loss: 0.5825 - val_acc: 0.6889
Epoch 27/150
105/105 [==============================] - 0s 195us/sample - loss: 0.5703 - acc: 0.7048 - val_loss: 0.6383 - val_acc: 0.6222
Epoch 28/150
105/105 [==============================] - 0s 180us/sample - loss: 0.5636 - acc: 0.7048 - val_loss: 0.6028 - val_acc: 0.6000
Epoch 29/150
105/105 [==============================] - 0s 204us/sample - loss: 0.5556 - acc: 0.7333 - val_loss: 0.6040 - val_acc: 0.6222
Epoch 30/150
105/105 [==============================] - 0s 205us/sample - loss: 0.5449 - acc: 0.7333 - val_loss: 0.6204 - val_acc: 0.6222
Epoch 31/150
105/105 [==============================] - 0s 187us/sample - loss: 0.5537 - acc: 0.7333 - val_loss: 0.6227 - val_acc: 0.6222
Epoch 32/150
105/105 [==============================] - 0s 182us/sample - loss: 0.5339 - acc: 0.7143 - val_loss: 0.5976 - val_acc: 0.6222
Epoch 33/150
105/105 [==============================] - 0s 199us/sample - loss: 0.5351 - acc: 0.7429 - val_loss: 0.5969 - val_acc: 0.6222
Epoch 34/150
105/105 [==============================] - 0s 180us/sample - loss: 0.5256 - acc: 0.6952 - val_loss: 0.5554 - val_acc: 0.6222
Epoch 35/150
105/105 [==============================] - 0s 203us/sample - loss: 0.5230 - acc: 0.7714 - val_loss: 0.5760 - val_acc: 0.6222
Epoch 36/150
105/105 [==============================] - 0s 179us/sample - loss: 0.5103 - acc: 0.7429 - val_loss: 0.5323 - val_acc: 0.8000
Epoch 37/150
105/105 [==============================] - 0s 185us/sample - loss: 0.5200 - acc: 0.7905 - val_loss: 0.5418 - val_acc: 0.6444
Epoch 38/150
105/105 [==============================] - 0s 177us/sample - loss: 0.5062 - acc: 0.7714 - val_loss: 0.5648 - val_acc: 0.6222
Epoch 39/150
105/105 [==============================] - 0s 211us/sample - loss: 0.5006 - acc: 0.7143 - val_loss: 0.5246 - val_acc: 0.8222
Epoch 40/150
105/105 [==============================] - 0s 206us/sample - loss: 0.5016 - acc: 0.7524 - val_loss: 0.5276 - val_acc: 0.6889
Epoch 41/150
105/105 [==============================] - 0s 176us/sample - loss: 0.4945 - acc: 0.7810 - val_loss: 0.5306 - val_acc: 0.6444
Epoch 42/150
105/105 [==============================] - 0s 202us/sample - loss: 0.4923 - acc: 0.8000 - val_loss: 0.5380 - val_acc: 0.6000
Epoch 43/150
105/105 [==============================] - 0s 181us/sample - loss: 0.4854 - acc: 0.7524 - val_loss: 0.5082 - val_acc: 0.8667
Epoch 44/150
105/105 [==============================] - 0s 188us/sample - loss: 0.4813 - acc: 0.7524 - val_loss: 0.5024 - val_acc: 0.8000
Epoch 45/150
105/105 [==============================] - 0s 183us/sample - loss: 0.4760 - acc: 0.8571 - val_loss: 0.5297 - val_acc: 0.6222
Epoch 46/150
105/105 [==============================] - 0s 190us/sample - loss: 0.4787 - acc: 0.7905 - val_loss: 0.5400 - val_acc: 0.6222
Epoch 47/150
105/105 [==============================] - 0s 188us/sample - loss: 0.4675 - acc: 0.7810 - val_loss: 0.5022 - val_acc: 0.8000
Epoch 48/150
105/105 [==============================] - 0s 184us/sample - loss: 0.4713 - acc: 0.8190 - val_loss: 0.5094 - val_acc: 0.6667
Epoch 49/150
105/105 [==============================] - 0s 189us/sample - loss: 0.4624 - acc: 0.7810 - val_loss: 0.4928 - val_acc: 0.8444
Epoch 50/150
105/105 [==============================] - 0s 204us/sample - loss: 0.4593 - acc: 0.8667 - val_loss: 0.4982 - val_acc: 0.7556
Epoch 51/150
105/105 [==============================] - 0s 207us/sample - loss: 0.4596 - acc: 0.8571 - val_loss: 0.4968 - val_acc: 0.7333
Epoch 52/150
105/105 [==============================] - 0s 173us/sample - loss: 0.4561 - acc: 0.8571 - val_loss: 0.5029 - val_acc: 0.6667
Epoch 53/150
105/105 [==============================] - 0s 196us/sample - loss: 0.4557 - acc: 0.8095 - val_loss: 0.5233 - val_acc: 0.6222
Epoch 54/150
105/105 [==============================] - 0s 188us/sample - loss: 0.4554 - acc: 0.7619 - val_loss: 0.4766 - val_acc: 0.8889
Epoch 55/150
105/105 [==============================] - 0s 175us/sample - loss: 0.4574 - acc: 0.8190 - val_loss: 0.4802 - val_acc: 0.8222
Epoch 56/150
105/105 [==============================] - 0s 182us/sample - loss: 0.4436 - acc: 0.8667 - val_loss: 0.4783 - val_acc: 0.8000
Epoch 57/150
105/105 [==============================] - 0s 181us/sample - loss: 0.4419 - acc: 0.8571 - val_loss: 0.4751 - val_acc: 0.8444
Epoch 58/150
105/105 [==============================] - 0s 212us/sample - loss: 0.4396 - acc: 0.8667 - val_loss: 0.4842 - val_acc: 0.7111
Epoch 59/150
105/105 [==============================] - 0s 178us/sample - loss: 0.4401 - acc: 0.8095 - val_loss: 0.4633 - val_acc: 0.8889
Epoch 60/150
105/105 [==============================] - 0s 207us/sample - loss: 0.4318 - acc: 0.8762 - val_loss: 0.4681 - val_acc: 0.8222
Epoch 61/150
105/105 [==============================] - 0s 186us/sample - loss: 0.4342 - acc: 0.8857 - val_loss: 0.4700 - val_acc: 0.8000
Epoch 62/150
105/105 [==============================] - 0s 207us/sample - loss: 0.4273 - acc: 0.8571 - val_loss: 0.4691 - val_acc: 0.7778
Epoch 63/150
105/105 [==============================] - 0s 194us/sample - loss: 0.4288 - acc: 0.8667 - val_loss: 0.4620 - val_acc: 0.8222
Epoch 64/150
105/105 [==============================] - 0s 183us/sample - loss: 0.4248 - acc: 0.8571 - val_loss: 0.4540 - val_acc: 0.8889
Epoch 65/150
105/105 [==============================] - 0s 185us/sample - loss: 0.4197 - acc: 0.8952 - val_loss: 0.4868 - val_acc: 0.6444
Epoch 66/150
105/105 [==============================] - 0s 194us/sample - loss: 0.4247 - acc: 0.8381 - val_loss: 0.4654 - val_acc: 0.7556
Epoch 67/150
105/105 [==============================] - 0s 191us/sample - loss: 0.4189 - acc: 0.8762 - val_loss: 0.4518 - val_acc: 0.8667
Epoch 68/150
105/105 [==============================] - 0s 196us/sample - loss: 0.4102 - acc: 0.9143 - val_loss: 0.4855 - val_acc: 0.6444
Epoch 69/150
105/105 [==============================] - 0s 184us/sample - loss: 0.4183 - acc: 0.8762 - val_loss: 0.4918 - val_acc: 0.6444
Epoch 70/150
105/105 [==============================] - 0s 251us/sample - loss: 0.4128 - acc: 0.8476 - val_loss: 0.4719 - val_acc: 0.7111
Epoch 71/150
105/105 [==============================] - 0s 205us/sample - loss: 0.4170 - acc: 0.8667 - val_loss: 0.4629 - val_acc: 0.7556
Epoch 72/150
105/105 [==============================] - 0s 206us/sample - loss: 0.4138 - acc: 0.8667 - val_loss: 0.4608 - val_acc: 0.7556
Epoch 73/150
105/105 [==============================] - 0s 191us/sample - loss: 0.4059 - acc: 0.8571 - val_loss: 0.4390 - val_acc: 0.8889
Epoch 74/150
105/105 [==============================] - 0s 184us/sample - loss: 0.3972 - acc: 0.8762 - val_loss: 0.4334 - val_acc: 0.8889
Epoch 75/150
105/105 [==============================] - 0s 179us/sample - loss: 0.4010 - acc: 0.9238 - val_loss: 0.4376 - val_acc: 0.8667
Epoch 76/150
105/105 [==============================] - 0s 224us/sample - loss: 0.3999 - acc: 0.9048 - val_loss: 0.4665 - val_acc: 0.7111
Epoch 77/150
105/105 [==============================] - 0s 248us/sample - loss: 0.3960 - acc: 0.8952 - val_loss: 0.4277 - val_acc: 0.8889
Epoch 78/150
105/105 [==============================] - 0s 216us/sample - loss: 0.3950 - acc: 0.9143 - val_loss: 0.4282 - val_acc: 0.8889
Epoch 79/150
105/105 [==============================] - 0s 214us/sample - loss: 0.3949 - acc: 0.9143 - val_loss: 0.4301 - val_acc: 0.8889
Epoch 80/150
105/105 [==============================] - 0s 201us/sample - loss: 0.3910 - acc: 0.8952 - val_loss: 0.4376 - val_acc: 0.8000
Epoch 81/150
105/105 [==============================] - 0s 190us/sample - loss: 0.3900 - acc: 0.9048 - val_loss: 0.4307 - val_acc: 0.8667
Epoch 82/150
105/105 [==============================] - 0s 209us/sample - loss: 0.3818 - acc: 0.9238 - val_loss: 0.4358 - val_acc: 0.7778
Epoch 83/150
105/105 [==============================] - 0s 189us/sample - loss: 0.3814 - acc: 0.9333 - val_loss: 0.4272 - val_acc: 0.8667
Epoch 84/150
105/105 [==============================] - 0s 206us/sample - loss: 0.3834 - acc: 0.9238 - val_loss: 0.4293 - val_acc: 0.8000
Epoch 85/150
105/105 [==============================] - 0s 206us/sample - loss: 0.3772 - acc: 0.9333 - val_loss: 0.4322 - val_acc: 0.7778
Epoch 86/150
105/105 [==============================] - 0s 199us/sample - loss: 0.3824 - acc: 0.8952 - val_loss: 0.4477 - val_acc: 0.7556
Epoch 87/150
105/105 [==============================] - 0s 209us/sample - loss: 0.3834 - acc: 0.8571 - val_loss: 0.4110 - val_acc: 0.9111
Epoch 88/150
105/105 [==============================] - 0s 191us/sample - loss: 0.3843 - acc: 0.9048 - val_loss: 0.4233 - val_acc: 0.8000
Epoch 89/150
105/105 [==============================] - 0s 181us/sample - loss: 0.3773 - acc: 0.9238 - val_loss: 0.4438 - val_acc: 0.7556
Epoch 90/150
105/105 [==============================] - 0s 176us/sample - loss: 0.3799 - acc: 0.9143 - val_loss: 0.4452 - val_acc: 0.7333
Epoch 91/150
105/105 [==============================] - 0s 184us/sample - loss: 0.3712 - acc: 0.9238 - val_loss: 0.4138 - val_acc: 0.8889
Epoch 92/150
105/105 [==============================] - 0s 185us/sample - loss: 0.3707 - acc: 0.9143 - val_loss: 0.4103 - val_acc: 0.8889
Epoch 93/150
105/105 [==============================] - 0s 180us/sample - loss: 0.3667 - acc: 0.9333 - val_loss: 0.4288 - val_acc: 0.7778
Epoch 94/150
105/105 [==============================] - 0s 181us/sample - loss: 0.3637 - acc: 0.9429 - val_loss: 0.4195 - val_acc: 0.7778
Epoch 95/150
105/105 [==============================] - 0s 187us/sample - loss: 0.3609 - acc: 0.9143 - val_loss: 0.4067 - val_acc: 0.8889
Epoch 96/150
105/105 [==============================] - 0s 182us/sample - loss: 0.3626 - acc: 0.9238 - val_loss: 0.3990 - val_acc: 0.9111
Epoch 97/150
105/105 [==============================] - 0s 193us/sample - loss: 0.3601 - acc: 0.9333 - val_loss: 0.3997 - val_acc: 0.8889
Epoch 98/150
105/105 [==============================] - 0s 201us/sample - loss: 0.3565 - acc: 0.9524 - val_loss: 0.4165 - val_acc: 0.8000
Epoch 99/150
105/105 [==============================] - 0s 229us/sample - loss: 0.3559 - acc: 0.9524 - val_loss: 0.4119 - val_acc: 0.8000
Epoch 100/150
105/105 [==============================] - 0s 181us/sample - loss: 0.3584 - acc: 0.9429 - val_loss: 0.4194 - val_acc: 0.8000
Epoch 101/150
105/105 [==============================] - 0s 183us/sample - loss: 0.3597 - acc: 0.9238 - val_loss: 0.3982 - val_acc: 0.8889
Epoch 102/150
105/105 [==============================] - 0s 191us/sample - loss: 0.3532 - acc: 0.9429 - val_loss: 0.4264 - val_acc: 0.7778
Epoch 103/150
105/105 [==============================] - 0s 193us/sample - loss: 0.3530 - acc: 0.8952 - val_loss: 0.3894 - val_acc: 0.9111
Epoch 104/150
105/105 [==============================] - 0s 187us/sample - loss: 0.3541 - acc: 0.9429 - val_loss: 0.4014 - val_acc: 0.8444
Epoch 105/150
105/105 [==============================] - 0s 202us/sample - loss: 0.3478 - acc: 0.9524 - val_loss: 0.4066 - val_acc: 0.8000
Epoch 106/150
105/105 [==============================] - 0s 189us/sample - loss: 0.3455 - acc: 0.9333 - val_loss: 0.4090 - val_acc: 0.8000
Epoch 107/150
105/105 [==============================] - 0s 182us/sample - loss: 0.3503 - acc: 0.9333 - val_loss: 0.4089 - val_acc: 0.8000
Epoch 108/150
105/105 [==============================] - 0s 179us/sample - loss: 0.3405 - acc: 0.9333 - val_loss: 0.4453 - val_acc: 0.7111
Epoch 109/150
105/105 [==============================] - 0s 182us/sample - loss: 0.3491 - acc: 0.8762 - val_loss: 0.3924 - val_acc: 0.8889
Epoch 110/150
105/105 [==============================] - 0s 197us/sample - loss: 0.3409 - acc: 0.9524 - val_loss: 0.3967 - val_acc: 0.8222
Epoch 111/150
105/105 [==============================] - 0s 202us/sample - loss: 0.3383 - acc: 0.9429 - val_loss: 0.3912 - val_acc: 0.8889
Epoch 112/150
105/105 [==============================] - 0s 187us/sample - loss: 0.3404 - acc: 0.9524 - val_loss: 0.4063 - val_acc: 0.8000
Epoch 113/150
105/105 [==============================] - 0s 190us/sample - loss: 0.3386 - acc: 0.9429 - val_loss: 0.3762 - val_acc: 0.9111
Epoch 114/150
105/105 [==============================] - 0s 186us/sample - loss: 0.3422 - acc: 0.9524 - val_loss: 0.3753 - val_acc: 0.9111
Epoch 115/150
105/105 [==============================] - 0s 189us/sample - loss: 0.3404 - acc: 0.9429 - val_loss: 0.3732 - val_acc: 0.9111
Epoch 116/150
105/105 [==============================] - 0s 187us/sample - loss: 0.3394 - acc: 0.9524 - val_loss: 0.3860 - val_acc: 0.8889
Epoch 117/150
105/105 [==============================] - 0s 193us/sample - loss: 0.3361 - acc: 0.9524 - val_loss: 0.4034 - val_acc: 0.8000
Epoch 118/150
105/105 [==============================] - 0s 183us/sample - loss: 0.3313 - acc: 0.9429 - val_loss: 0.3887 - val_acc: 0.8444
Epoch 119/150
105/105 [==============================] - 0s 188us/sample - loss: 0.3298 - acc: 0.9524 - val_loss: 0.3967 - val_acc: 0.8000
Epoch 120/150
105/105 [==============================] - 0s 178us/sample - loss: 0.3305 - acc: 0.9238 - val_loss: 0.3858 - val_acc: 0.8667
Epoch 121/150
105/105 [==============================] - 0s 179us/sample - loss: 0.3315 - acc: 0.9429 - val_loss: 0.3797 - val_acc: 0.8889
Epoch 122/150
105/105 [==============================] - 0s 180us/sample - loss: 0.3302 - acc: 0.9524 - val_loss: 0.3704 - val_acc: 0.9111
Epoch 123/150
105/105 [==============================] - 0s 181us/sample - loss: 0.3271 - acc: 0.9524 - val_loss: 0.3686 - val_acc: 0.9111
Epoch 124/150
105/105 [==============================] - 0s 175us/sample - loss: 0.3253 - acc: 0.9429 - val_loss: 0.3688 - val_acc: 0.9111
Epoch 125/150
105/105 [==============================] - 0s 183us/sample - loss: 0.3237 - acc: 0.9714 - val_loss: 0.3931 - val_acc: 0.8000
Epoch 126/150
105/105 [==============================] - 0s 178us/sample - loss: 0.3246 - acc: 0.9429 - val_loss: 0.3890 - val_acc: 0.8000
Epoch 127/150
105/105 [==============================] - 0s 177us/sample - loss: 0.3281 - acc: 0.9429 - val_loss: 0.3739 - val_acc: 0.8889
Epoch 128/150
105/105 [==============================] - 0s 179us/sample - loss: 0.3215 - acc: 0.9524 - val_loss: 0.3813 - val_acc: 0.8444
Epoch 129/150
105/105 [==============================] - 0s 177us/sample - loss: 0.3210 - acc: 0.9429 - val_loss: 0.3755 - val_acc: 0.8889
Epoch 130/150
105/105 [==============================] - 0s 207us/sample - loss: 0.3183 - acc: 0.9429 - val_loss: 0.3631 - val_acc: 0.9111
Epoch 131/150
105/105 [==============================] - 0s 180us/sample - loss: 0.3149 - acc: 0.9619 - val_loss: 0.3583 - val_acc: 0.9111
Epoch 132/150
105/105 [==============================] - 0s 177us/sample - loss: 0.3150 - acc: 0.9619 - val_loss: 0.3671 - val_acc: 0.8889
Epoch 133/150
105/105 [==============================] - 0s 183us/sample - loss: 0.3157 - acc: 0.9524 - val_loss: 0.3866 - val_acc: 0.8000
Epoch 134/150
105/105 [==============================] - 0s 181us/sample - loss: 0.3145 - acc: 0.9524 - val_loss: 0.3686 - val_acc: 0.8889
Epoch 135/150
105/105 [==============================] - 0s 181us/sample - loss: 0.3109 - acc: 0.9333 - val_loss: 0.3553 - val_acc: 0.9111
Epoch 136/150
105/105 [==============================] - 0s 189us/sample - loss: 0.3132 - acc: 0.9524 - val_loss: 0.3539 - val_acc: 0.9111
Epoch 137/150
105/105 [==============================] - 0s 188us/sample - loss: 0.3132 - acc: 0.9524 - val_loss: 0.3620 - val_acc: 0.8889
Epoch 138/150
105/105 [==============================] - 0s 231us/sample - loss: 0.3089 - acc: 0.9524 - val_loss: 0.3554 - val_acc: 0.9111
Epoch 139/150
105/105 [==============================] - 0s 176us/sample - loss: 0.3076 - acc: 0.9714 - val_loss: 0.3654 - val_acc: 0.9111
Epoch 140/150
105/105 [==============================] - 0s 206us/sample - loss: 0.3077 - acc: 0.9524 - val_loss: 0.3706 - val_acc: 0.8444
Epoch 141/150
105/105 [==============================] - 0s 199us/sample - loss: 0.3085 - acc: 0.9429 - val_loss: 0.3498 - val_acc: 0.9111
Epoch 142/150
105/105 [==============================] - 0s 212us/sample - loss: 0.3041 - acc: 0.9619 - val_loss: 0.3531 - val_acc: 0.9111
Epoch 143/150
105/105 [==============================] - 0s 221us/sample - loss: 0.3054 - acc: 0.9619 - val_loss: 0.3705 - val_acc: 0.8444
Epoch 144/150
105/105 [==============================] - 0s 241us/sample - loss: 0.3057 - acc: 0.9524 - val_loss: 0.3619 - val_acc: 0.9111
Epoch 145/150

### Model Training

In [118]:
y_predict=model.predict_classes(x_train)
scores = model.evaluate(x_train, y_train)
scores[1]*100

105/105 [==============================] - 0s 99us/sample - loss: 0.2954 - acc: 0.9619

96.1904764175415

### Model Prediction

In [119]:
scores = model.evaluate(x_test, y_test)
scores[1]*100

45/45 [==============================] - 0s 231us/sample - loss: 0.3421 - acc: 0.9111

91.11111164093018

### Save the Model

In [0]:
model.save('Keras')

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?